FROM aifrak/testinfra:5.2.2-python-3.8.5-slim-buster as test-testinfra

RUN set -ex \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  # install dependencies
  && apt-get install --yes --no-install-recommends \
  ca-certificates=* \
  git=* \
  sudo=* \
  # clean cache and temporary files
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip install --no-cache-dir pytest-order==0.11.0

ARG USER=dev-user
ARG GROUP=$USER
ARG DOCKER_TEST_DIR=/home/$USER/docker

RUN \
  groupadd --gid 1000 $USER \
  && useradd --uid 1000 --gid $GROUP --shell /bin/bash --create-home $USER

WORKDIR $DOCKER_TEST_DIR

COPY --chown=$USER:$GROUP . .

RUN \
  export DEBIAN_FRONTEND=noninteractive \
  && ./install $USER \
  --zsh --dependencies --node --fonts --dockerfile --shellscript --elixir
