[settings]
env_shell_expand = true

[tools]
# -- programming languages
go = "1.26.2"
node = "lts"
rust = "1.95.0"
python = "3.14.4"
yarn = "latest"

# -- terminal tools
oh-my-posh = "latest"
opencode = "latest"
fzf = "latest"
lsd = "latest"

# -- neovim tools
neovim = "stable"
tree-sitter = "latest"
typstyle = "latest"
# elixir LSP
"aqua:expert-lsp/expert" = "latest"
# snacks.nvim (picker)
ripgrep = "latest"
# snacks.nvim (lazygit)
lazygit = "latest"
# snacks.nvim (picker)
fd = "latest"

[env]
XDG_CONFIG_HOME = "{{ .chezmoi.homeDir }}/.config"
# keep elixir iex history
ERL_AFLAGS = "-kernel shell_history enabled"
