[settings]
env_shell_expand = true

[tools]
# -- package managers (node)
pnpm = "latest"
# used by mise
aube = "latest"
# used by Neovim plugin
yarn = "latest"

# -- package managers (python)
uv = "latest"

# -- programming languages
go = "1.26.2"
node = "lts"
rust = "1.95.0"
python = "3.14.4"

# -- terminal tools
oh-my-posh = "latest"
opencode = "latest"
fzf = "latest"
lsd = "latest"

# -- neovim tools
neovim = "stable"
tree-sitter = "latest"
typstyle = "latest"
# elixir LSP
"aqua:expert-lsp/expert" = "latest"
# snacks.nvim (picker)
ripgrep = "latest"
# snacks.nvim (lazygit)
lazygit = "latest"
# snacks.nvim (picker)
fd = "latest"

# -- AI skills
"npm:skills" = "latest"

[env]
{{ if .isPersonal }}
MISE_GITHUB_TOKEN = "{{ keepassxcAttribute "GitHub" "PAT_CRAWL_REPOS" }}"
CONTEXT7_API_KEY = "{{ keepassxcAttribute "Context7" "API key" }}"
{{ end }}
XDG_CONFIG_HOME = "{{ .chezmoi.homeDir }}/.config"
# keep elixir iex history
ERL_AFLAGS = "-kernel shell_history enabled"
