[env]
# Fix for Windows and Neovim - blink.cmp (Rust fuzzy search)
RUSTUP_TOOLCHAIN = "stable-x86_64-pc-windows-gnu"
# Fix error when running below:
# :lua require("nvim-treesitter").install("regex"):wait()
CC = "gcc"
